= Cheatsheets

[[AddressResolverOptions]]
== AddressResolverOptions

++++
 Configuration options for Vert.x hostname resolver. The resolver uses the local <i>hosts</i> file and performs
 DNS <i>A</i> and <i>AAAA</i> queries.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[cacheMaxTimeToLive]]`@cacheMaxTimeToLive`|`Number (int)`|+++
Set the cache maximum TTL value in seconds. After successful resolution IP addresses are cached with their DNS response TTL,
 use this to set a maximum value to all responses TTL.
+++
|[[cacheMinTimeToLive]]`@cacheMinTimeToLive`|`Number (int)`|+++
Set the cache minimum TTL value in seconds. After resolution successful IP addresses are cached with their DNS response TTL,
 use this to set a minimum value to all responses TTL.
+++
|[[cacheNegativeTimeToLive]]`@cacheNegativeTimeToLive`|`Number (int)`|+++
Set the negative cache TTL value in seconds. After a failed hostname resolution, DNS queries won't be retried
 for a period of time equals to the negative TTL. This allows to reduce the response time of negative replies
 and reduce the amount of messages to DNS servers.
+++
|[[hostsPath]]`@hostsPath`|`String`|+++
Set the path of an alternate hosts configuration file to use instead of the one provided by the os.
 <p/>
 The default value is null, so the operating system hosts config is used.
+++
|[[hostsValue]]`@hostsValue`|`Buffer`|+++
Set an alternate hosts configuration file to use instead of the one provided by the os.
 <p/>
 The value should contain the hosts content literaly, for instance <i>127.0.0.1 localhost</i>
 <p/>
 The default value is null, so the operating system hosts config is used.
+++
|[[maxQueries]]`@maxQueries`|`Number (int)`|+++
Set the maximum number of queries when an hostname is resolved.
+++
|[[ndots]]`@ndots`|`Number (int)`|+++
Set the ndots value used when resolving using search domains, the default value is <code>-1</code> which
 determines the value from the OS on Linux or uses the value <code>1</code>.
+++
|[[optResourceEnabled]]`@optResourceEnabled`|`Boolean`|+++
Set to true to enable the automatic inclusion in DNS queries of an optional record that hints
 the remote DNS server about how much data the resolver can read per response.
+++
|[[queryTimeout]]`@queryTimeout`|`Number (long)`|+++
Set the query timeout in milliseconds, i.e the amount of time after a query is considered to be failed.
+++
|[[rdFlag]]`@rdFlag`|`Boolean`|+++
Set the DNS queries <i>Recursion Desired</i> flag value.
+++
|[[rotateServers]]`@rotateServers`|`Boolean`|+++
Set to <code>true</code> to enable round-robin selection of the dns server to use. It spreads the query load
 among the servers and avoids all lookup to hit the first server of the list.
+++
|[[searchDomains]]`@searchDomains`|`Array of String`|+++
Set the lists of DNS search domains.
 <p/>
 When the search domain list is null, the effective search domain list will be populated using
 the system DNS search domains.
+++
|[[servers]]`@servers`|`Array of String`|+++
Set the list of DNS server addresses, an address is the IP  of the dns server, followed by an optional
 colon and a port, e.g <code>8.8.8.8</code> or {code 192.168.0.1:40000}. When the list is empty, the resolver
 will use the list of the system DNS server addresses from the environment, if that list cannot be retrieved
 it will use Google's public DNS servers <code>"8.8.8.8"</code> and <code>"8.8.4.4"</code>.
+++
|===

[[AggregateOptions]]
== AggregateOptions

++++
 Options used to configure aggregate operations.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[allowDiskUse]]`@allowDiskUse`|`Boolean`|+++
Set the flag if writing to temporary files is enabled.
+++
|[[batchSize]]`@batchSize`|`Number (int)`|+++
Set the batch size for methods loading found data in batches.
+++
|[[maxTime]]`@maxTime`|`Number (long)`|+++
Set the time limit in milliseconds for processing operations on a cursor.
+++
|===

[[Argument]]
== Argument

++++
 Defines a command line argument. Unlike options, argument don't have names and are identified using an index. The
 first index is 0 (because we are in the computer world).
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[argName]]`@argName`|`String`|+++
Sets the argument name of this link.
+++
|[[defaultValue]]`@defaultValue`|`String`|+++
Sets the default value of this link.
+++
|[[description]]`@description`|`String`|+++
Sets the description of the link.
+++
|[[hidden]]`@hidden`|`Boolean`|+++
Sets whether or not the current link is hidden.
+++
|[[index]]`@index`|`Number (int)`|+++
Sets the argument index.
+++
|[[multiValued]]`@multiValued`|`Boolean`|+++
Sets whether or not the argument can receive several values. Only the last argument can receive several values.
+++
|[[required]]`@required`|`Boolean`|+++
Sets whether or not the current link is required.
+++
|===

[[BridgeOptions]]
== BridgeOptions

++++
 Specify the event bus bridge options.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[BulkOperation]]
== BulkOperation

++++
 Contains all data needed for one operation of a bulk write operation.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[document]]`@document`|`Json object`|+++
Sets the document, used by insert, replace, and update operations
+++
|[[filter]]`@filter`|`Json object`|+++
Sets the filter document, used by replace, update, and delete operations
+++
|[[multi]]`@multi`|`Boolean`|+++
Sets the multi flag, used by update and delete operations
+++
|[[type]]`@type`|`link:enums.html#BulkOperationType[BulkOperationType]`|+++
Sets the operation type
+++
|[[upsert]]`@upsert`|`Boolean`|+++
Sets the upsert flag, used by update and replace operations
+++
|===

[[BulkWriteOptions]]
== BulkWriteOptions

++++
 Options for configuring bulk write operations.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[ordered]]`@ordered`|`Boolean`|+++
Set the ordered option
+++
|[[writeOption]]`@writeOption`|`link:enums.html#WriteOption[WriteOption]`|+++
Set the write option
+++
|===

[[ClientOptionsBase]]
== ClientOptionsBase

++++
 Base class for Client options
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`@connectTimeout`|`Number (int)`|+++
Set the connect timeout
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[localAddress]]`@localAddress`|`String`|+++
Set the local interface to bind for network connections. When the local address is null,
 it will pick any local address, the default local address is null.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[metricsName]]`@metricsName`|`String`|+++
Set the metrics name identifying the reported metrics, useful for grouping metrics
 with the same name.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[trustAll]]`@trustAll`|`Boolean`|+++
Set whether all server certificates should be trusted
+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|===

[[ConfigChange]]
== ConfigChange

++++
 A structure representing a configuration change.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[newConfiguration]]`@newConfiguration`|`Json object`|+++
Sets the new configuration.
+++
|[[previousConfiguration]]`@previousConfiguration`|`Json object`|+++
Sets the previous configuration.
+++
|===

[[ConfigRetrieverOptions]]
== ConfigRetrieverOptions

++++
 Options to configure the <code>ConfigRetriever</code>.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[includeDefaultStores]]`@includeDefaultStores`|`Boolean`|+++
Enables or disables the inclusion of the default stored in the configuration.
+++
|[[scanPeriod]]`@scanPeriod`|`Number (long)`|+++
Configures the scan period, in ms. This is the time amount between two checks of the configuration updates.
+++
|===

[[ConfigStoreOptions]]
== ConfigStoreOptions

++++
 Data object representing the configuration of a configuration store. This object describes the configuration of a
 chunk of configuration that you retrieve. It specifies its type (type of configuration store), the format of the
 retrieved configuration chunk, and you can also configures the store if it needs configuration to
 retrieve the configuration chunk.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets the configuration of the store
+++
|[[format]]`@format`|`String`|+++
Sets the format of the configuration that is retrieved from the store.
+++
|[[optional]]`@optional`|`Boolean`|+++
Sets whether or not the store is optional. When the configuration is retrieve, if an optional store
 returns a failure, the failure is ignored and an empty json object is used instead (for this store).
+++
|[[type]]`@type`|`String`|+++
Sets the configuration type
+++
|===

[[CopyOptions]]
== CopyOptions

++++
 Describes the copy (and move) options.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[atomicMove]]`@atomicMove`|`Boolean`|+++
Whether move should be performed as an atomic filesystem operation. Defaults to <code>false</code>.
+++
|[[copyAttributes]]`@copyAttributes`|`Boolean`|+++
Whether the file attributes should be copied. Defaults to <code>false</code>.
+++
|[[nofollowLinks]]`@nofollowLinks`|`Boolean`|+++
Whether symbolic links should not be followed during copy or move operations. Defaults to <code>false</code>.
+++
|[[replaceExisting]]`@replaceExisting`|`Boolean`|+++
Whether an existing file, empty directory, or link should be replaced. Defaults to <code>false</code>.
+++
|===

[[DatagramSocketOptions]]
== DatagramSocketOptions

++++
 Options used to configure a datagram socket.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[broadcast]]`@broadcast`|`Boolean`|+++
Set if the socket can send or receive broadcast packets
+++
|[[ipV6]]`@ipV6`|`Boolean`|+++
Set if IP v6 should be used
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[loopbackModeDisabled]]`@loopbackModeDisabled`|`Boolean`|+++
Set if loopback mode is disabled
+++
|[[multicastNetworkInterface]]`@multicastNetworkInterface`|`String`|+++
Set the multicast network interface address
+++
|[[multicastTimeToLive]]`@multicastTimeToLive`|`Number (int)`|+++
Set the multicast ttl value
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|===

[[DeliveryOptions]]
== DeliveryOptions

++++
 Delivery options are used to configure message delivery.
 <p>
 Delivery options allow to configure delivery timeout and message codec name, and to provide any headers
 that you wish to send with the message.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[codecName]]`@codecName`|`String`|+++
Set the codec name.
+++
|[[headers]]`@headers`|`String`|+++
Add a message header.
 <p>
 Message headers can be sent with any message and will be accessible with link
 at the recipient.
+++
|[[localOnly]]`@localOnly`|`Boolean`|+++
Whether a message should be delivered to local consumers only. Defaults to <code>false</code>.

 <p>
 <strong>This option is effective in clustered mode only and does not apply to reply messages</strong>.
+++
|[[sendTimeout]]`@sendTimeout`|`Number (long)`|+++
Set the send timeout.
+++
|===

[[DeploymentOptions]]
== DeploymentOptions

++++
 Options for configuring a verticle deployment.
 <p>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Set the JSON configuration that will be passed to the verticle(s) when it's deployed
+++
|[[ha]]`@ha`|`Boolean`|+++
Set whether the verticle(s) will be deployed as HA.
+++
|[[instances]]`@instances`|`Number (int)`|+++
Set the number of instances that should be deployed.
+++
|[[maxWorkerExecuteTime]]`@maxWorkerExecuteTime`|`Number (long)`|+++
Sets the value of max worker execute time, in link.
 <p>
 The default value of link is
+++
|[[maxWorkerExecuteTimeUnit]]`@maxWorkerExecuteTimeUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the time unit of <code>maxWorkerExecuteTime</code>
+++
|[[worker]]`@worker`|`Boolean`|+++
Set whether the verticle(s) should be deployed as a worker verticle
+++
|[[workerPoolName]]`@workerPoolName`|`String`|+++
Set the worker pool name to use for this verticle. When no name is set, the Vert.x
 worker pool will be used, when a name is set, the verticle will use a named worker pool.
+++
|[[workerPoolSize]]`@workerPoolSize`|`Number (int)`|+++
Set the maximum number of worker threads to be used by the Vert.x instance.
+++
|===

[[DnsClientOptions]]
== DnsClientOptions

++++
 Configuration options for Vert.x DNS client.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[host]]`@host`|`String`|+++
Set the host name to be used by this client in requests.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[port]]`@port`|`Number (int)`|+++
Set the port to be used by this client in requests.
+++
|[[queryTimeout]]`@queryTimeout`|`Number (long)`|+++
Set the query timeout in milliseconds, i.e the amount of time after a query is considered to be failed.
+++
|[[recursionDesired]]`@recursionDesired`|`Boolean`|+++
Set whether or not recursion is desired
+++
|===

[[EventBusOptions]]
== EventBusOptions

++++
 Options to configure the event bus.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`@acceptBacklog`|`Number (int)`|+++
Set the accept back log.
+++
|[[clientAuth]]`@clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|+++
Set whether client auth is required
+++
|[[clusterNodeMetadata]]`@clusterNodeMetadata`|`Json object`|+++
Set information about this node when Vert.x is clustered.
 <p>
 The data may be used by the link to select a node for a given message.
 For example, it could be used to implement a partioning strategy.
 <p>
 The default link does not use the node metadata.
+++
|[[clusterPingInterval]]`@clusterPingInterval`|`Number (long)`|+++
Set the value of cluster ping interval, in ms.
+++
|[[clusterPingReplyInterval]]`@clusterPingReplyInterval`|`Number (long)`|+++
Set the value of cluster ping reply interval, in ms.
+++
|[[clusterPublicHost]]`@clusterPublicHost`|`String`|+++
Set the public facing hostname to be used for clustering.
 Sometimes, e.g. when running on certain clouds, the local address the server listens on for clustering is
 not the same address that other nodes connect to it at, as the OS / cloud infrastructure does some kind of
 proxying. If this is the case you can specify a public hostname which is different from the hostname the
 server listens at.
 <p>
 The default value is null which means use the same as the cluster hostname.
+++
|[[clusterPublicPort]]`@clusterPublicPort`|`Number (int)`|+++
See link for an explanation.
+++
|[[connectTimeout]]`@connectTimeout`|`Number (int)`|+++
Sets the connect timeout
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[host]]`@host`|`String`|+++
Sets the host. Defaults to <code>null</code>.
 <p>
 When the clustered eventbus starts, it tries to bind to the provided <code>host</code>.
 If <code>host</code> is <code>null</code>, then it tries to bind to the same host as the underlying cluster manager.
 As a last resort, an address will be picked among the available network interfaces.
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[port]]`@port`|`Number (int)`|+++
Sets the port.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reconnectAttempts]]`@reconnectAttempts`|`Number (int)`|+++
Sets the value of reconnect attempts.
+++
|[[reconnectInterval]]`@reconnectInterval`|`Number (long)`|+++
Set the reconnect interval.
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[trustAll]]`@trustAll`|`Boolean`|+++
Set whether all server certificates should be trusted.
+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|===

[[FileSystemOptions]]
== FileSystemOptions

++++
 Vert.x file system base configuration, this class can be extended by provider implementations to configure
 those specific implementations.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[classPathResolvingEnabled]]`@classPathResolvingEnabled`|`Boolean`|+++
When vert.x cannot find the file on the filesystem it tries to resolve the
 file from the class path when this is set to <code>true</code>.
+++
|[[fileCacheDir]]`@fileCacheDir`|`String`|+++
When vert.x reads a file that is packaged with the application it gets
 extracted to this directory first and subsequent reads will use the extracted
 file to get better IO performance.
+++
|[[fileCachingEnabled]]`@fileCachingEnabled`|`Boolean`|+++
Set to <code>true</code> to cache files on the real file system
 when the filesystem performs class path resolving.
+++
|===

[[FindOptions]]
== FindOptions

++++
 Options used to configure find operations.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchSize]]`@batchSize`|`Number (int)`|+++
Set the batch size for methods loading found data in batches.
+++
|[[fields]]`@fields`|`Json object`|+++
Set the fields
+++
|[[limit]]`@limit`|`Number (int)`|+++
Set the limit
+++
|[[skip]]`@skip`|`Number (int)`|+++
Set the skip
+++
|[[sort]]`@sort`|`Json object`|+++
Set the sort document
+++
|===

[[GoAway]]
== GoAway

++++
 A  frame.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[debugData]]`@debugData`|`Buffer`|+++
Set the additional debug data
+++
|[[errorCode]]`@errorCode`|`Number (long)`|+++

+++
|[[lastStreamId]]`@lastStreamId`|`Number (int)`|+++
Set the last stream id.
+++
|===

[[GridFsDownloadOptions]]
== GridFsDownloadOptions

++++
 Options used to configure downloads from GridFS.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[revision]]`@revision`|`Number (Integer)`|-
|===

[[GridFsUploadOptions]]
== GridFsUploadOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[chunkSizeBytes]]`@chunkSizeBytes`|`Number (Integer)`|-
|[[metadata]]`@metadata`|`Json object`|-
|===

[[HtdigestCredentials]]
== HtdigestCredentials

++++
 Credentials specific to the link authentication provider
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[algorithm]]`@algorithm`|`String`|-
|[[cnonce]]`@cnonce`|`String`|-
|[[method]]`@method`|`String`|-
|[[nc]]`@nc`|`String`|-
|[[nonce]]`@nonce`|`String`|-
|[[opaque]]`@opaque`|`String`|-
|[[qop]]`@qop`|`String`|-
|[[realm]]`@realm`|`String`|-
|[[response]]`@response`|`String`|-
|[[uri]]`@uri`|`String`|-
|[[username]]`@username`|`String`|-
|===

[[HtpasswdAuthOptions]]
== HtpasswdAuthOptions

++++
 Options configuring htpasswd authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[htpasswdFile]]`@htpasswdFile`|`String`|-
|[[plainTextEnabled]]`@plainTextEnabled`|`Boolean`|-
|===

[[Http2PushMapping]]
== Http2PushMapping


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[extensionTarget]]`@extensionTarget`|`String`|-
|[[filePath]]`@filePath`|`String`|-
|[[noPush]]`@noPush`|`Boolean`|-
|===

[[Http2Settings]]
== Http2Settings

++++
 HTTP2 settings, the settings is initialized with the default HTTP/2 values.<p>

 The settings expose the parameters defined by the HTTP/2 specification, as well as extra settings for
 protocol extensions.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[headerTableSize]]`@headerTableSize`|`Number (long)`|+++
Set  HTTP/2 setting.
+++
|[[initialWindowSize]]`@initialWindowSize`|`Number (int)`|+++
Set the  HTTP/2 setting
+++
|[[maxConcurrentStreams]]`@maxConcurrentStreams`|`Number (long)`|+++
Set the  HTTP/2 setting
+++
|[[maxFrameSize]]`@maxFrameSize`|`Number (int)`|+++
Set the  HTTP/2 setting
+++
|[[maxHeaderListSize]]`@maxHeaderListSize`|`Number (long)`|+++
Set the  HTTP/2 setting
+++
|[[pushEnabled]]`@pushEnabled`|`Boolean`|+++
Set the  HTTP/2 setting
+++
|===

[[HttpClientOptions]]
== HttpClientOptions

++++
 Options describing how an link will make connections.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[alpnVersions]]`@alpnVersions`|`Array of link:enums.html#HttpVersion[HttpVersion]`|+++
Set the list of protocol versions to provide to the server during the Application-Layer Protocol Negotiation.
 When the list is empty, the client provides a best effort list according to link:

 <ul>
   <li>: [ "h2", "http/1.1" ]</li>
   <li>otherwise: [link]</li>
 </ul>
+++
|[[connectTimeout]]`@connectTimeout`|`Number (int)`|+++
Set the connect timeout
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[decoderInitialBufferSize]]`@decoderInitialBufferSize`|`Number (int)`|+++
set to <code>initialBufferSizeHttpDecoder</code> the initial buffer of the HttpDecoder.
+++
|[[defaultHost]]`@defaultHost`|`String`|+++
Set the default host name to be used by this client in requests if none is provided when making the request.
+++
|[[defaultPort]]`@defaultPort`|`Number (int)`|+++
Set the default port to be used by this client in requests if none is provided when making the request.
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[forceSni]]`@forceSni`|`Boolean`|+++
By default, the server name is only sent for Fully Qualified Domain Name (FQDN), setting
 this property to <code>true</code> forces the server name to be always sent.
+++
|[[http2ClearTextUpgrade]]`@http2ClearTextUpgrade`|`Boolean`|+++
Set to <code>true</code> when an <i>h2c</i> connection is established using an HTTP/1.1 upgrade request, and <code>false</code>
 when an <i>h2c</i> connection is established directly (with prior knowledge).
+++
|[[http2ConnectionWindowSize]]`@http2ConnectionWindowSize`|`Number (int)`|+++
Set the default HTTP/2 connection window size. It overrides the initial window
 size set by link, so the connection window size
 is greater than for its streams, in order the data throughput.
 <p/>
 A value of <code>-1</code> reuses the initial window size setting.
+++
|[[http2KeepAliveTimeout]]`@http2KeepAliveTimeout`|`Number (int)`|+++
Set the keep alive timeout for HTTP/2 connections, in seconds.
 <p/>
 This value determines how long a connection remains unused in the pool before being evicted and closed.
 <p/>
 A timeout of <code>0</code> means there is no timeout.
+++
|[[http2MaxPoolSize]]`@http2MaxPoolSize`|`Number (int)`|+++
Set the maximum pool size for HTTP/2 connections
+++
|[[http2MultiplexingLimit]]`@http2MultiplexingLimit`|`Number (int)`|+++
Set a client limit of the number concurrent streams for each HTTP/2 connection, this limits the number
 of streams the client can create for a connection. The effective number of streams for a
 connection is the min of this value and the server's initial settings.
 <p/>
 Setting the value to <code>-1</code> means to use the value sent by the server's initial settings.
 <code>-1</code> is the default value.
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[keepAlive]]`@keepAlive`|`Boolean`|+++
Set whether keep alive is enabled on the client
+++
|[[keepAliveTimeout]]`@keepAliveTimeout`|`Number (int)`|+++
Set the keep alive timeout for HTTP/1.x, in seconds.
 <p/>
 This value determines how long a connection remains unused in the pool before being evicted and closed.
 <p/>
 A timeout of <code>0</code> means there is no timeout.
+++
|[[localAddress]]`@localAddress`|`String`|+++
Set the local interface to bind for network connections. When the local address is null,
 it will pick any local address, the default local address is null.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[maxChunkSize]]`@maxChunkSize`|`Number (int)`|+++
Set the maximum HTTP chunk size
+++
|[[maxHeaderSize]]`@maxHeaderSize`|`Number (int)`|+++
Set the maximum length of all headers for HTTP/1.x .
+++
|[[maxInitialLineLength]]`@maxInitialLineLength`|`Number (int)`|+++
Set the maximum length of the initial line for HTTP/1.x (e.g. <code>"HTTP/1.1 200 OK"</code>)
+++
|[[maxPoolSize]]`@maxPoolSize`|`Number (int)`|+++
Set the maximum pool size for connections
+++
|[[maxRedirects]]`@maxRedirects`|`Number (int)`|+++
Set to <code>maxRedirects</code> the maximum number of redirection a request can follow.
+++
|[[maxWaitQueueSize]]`@maxWaitQueueSize`|`Number (int)`|+++
Set the maximum requests allowed in the wait queue, any requests beyond the max size will result in
 a ConnectionPoolTooBusyException.  If the value is set to a negative number then the queue will be unbounded.
+++
|[[maxWebSocketFrameSize]]`@maxWebSocketFrameSize`|`Number (int)`|+++
Set the max WebSocket frame size
+++
|[[maxWebSocketMessageSize]]`@maxWebSocketMessageSize`|`Number (int)`|+++
Set the max WebSocket message size
+++
|[[metricsName]]`@metricsName`|`String`|+++
Set the metrics name identifying the reported metrics, useful for grouping metrics
 with the same name.
+++
|[[pipelining]]`@pipelining`|`Boolean`|+++
Set whether pipe-lining is enabled on the client
+++
|[[pipeliningLimit]]`@pipeliningLimit`|`Number (int)`|+++
Set the limit of pending requests a pipe-lined HTTP/1 connection can send.
+++
|[[poolCleanerPeriod]]`@poolCleanerPeriod`|`Number (int)`|+++
Set the connection pool cleaner period in milli seconds, a non positive value disables expiration checks and connections
 will remain in the pool until they are closed.
+++
|[[protocolVersion]]`@protocolVersion`|`link:enums.html#HttpVersion[HttpVersion]`|+++
Set the protocol version.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[sendUnmaskedFrames]]`@sendUnmaskedFrames`|`Boolean`|+++
Set <code>true</code> when the client wants to skip frame masking.
 <p>
 You may want to set it <code>true</code> on server by server WebSocket communication: in this case you are by passing
 RFC6455 protocol.
 <p>
 It's <code>false</code> as default.
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[trustAll]]`@trustAll`|`Boolean`|+++
Set whether all server certificates should be trusted
+++
|[[tryUseCompression]]`@tryUseCompression`|`Boolean`|+++
Set whether compression is enabled
+++
|[[tryUsePerFrameWebSocketCompression]]`@tryUsePerFrameWebSocketCompression`|`Boolean`|+++
Set whether the client will offer the WebSocket per-frame deflate compression extension.
+++
|[[tryUsePerMessageWebSocketCompression]]`@tryUsePerMessageWebSocketCompression`|`Boolean`|+++
Set whether the client will offer the WebSocket per-message deflate compression extension.
+++
|[[tryWebSocketDeflateFrameCompression]]`@tryWebSocketDeflateFrameCompression`|`Boolean`|+++

+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|[[verifyHost]]`@verifyHost`|`Boolean`|+++
Set whether hostname verification is enabled
+++
|[[webSocketCompressionAllowClientNoContext]]`@webSocketCompressionAllowClientNoContext`|`Boolean`|+++
Set whether the <code>client_no_context_takeover</code> parameter of the WebSocket per-message
 deflate compression extension will be offered.
+++
|[[webSocketCompressionLevel]]`@webSocketCompressionLevel`|`Number (int)`|+++
Set the WebSocket deflate compression level.
+++
|[[webSocketCompressionRequestServerNoContext]]`@webSocketCompressionRequestServerNoContext`|`Boolean`|+++
Set whether the <code>server_no_context_takeover</code> parameter of the WebSocket per-message
 deflate compression extension will be offered.
+++
|===

[[HttpMethod]]
== HttpMethod

++++
 Represents an HTTP method.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[HttpServerOptions]]
== HttpServerOptions

++++
 Represents options used by an link instance
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`@acceptBacklog`|`Number (int)`|+++
Set the accept back log
+++
|[[acceptUnmaskedFrames]]`@acceptUnmaskedFrames`|`Boolean`|+++
Set <code>true</code> when the server accepts unmasked frame.
 As default Server doesn't accept unmasked frame, you can bypass this behaviour (RFC 6455) setting <code>true</code>.
 It's set to <code>false</code> as default.
+++
|[[alpnVersions]]`@alpnVersions`|`Array of link:enums.html#HttpVersion[HttpVersion]`|+++
Set the list of protocol versions to provide to the server during the Application-Layer Protocol Negotiatiation.
+++
|[[clientAuth]]`@clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|+++
Set whether client auth is required
+++
|[[compressionLevel]]`@compressionLevel`|`Number (int)`|+++
This method allows to set the compression level to be used in http1.x/2 response bodies
 when compression support is turned on (@see setCompressionSupported) and the client advertises
 to support <code>deflate/gzip</code> compression in the <code>Accept-Encoding</code> header

 default value is : 6 (Netty legacy)

 The compression level determines how much the data is compressed on a scale from 1 to 9,
 where '9' is trying to achieve the maximum compression ratio while '1' instead is giving
 priority to speed instead of compression ratio using some algorithm optimizations and skipping
 pedantic loops that usually gives just little improvements

 While one can think that best value is always the maximum compression ratio,
 there's a trade-off to consider: the most compressed level requires the most
 computational work to compress/decompress data, e.g. more dictionary lookups and loops.

 E.g. you have it set fairly high on a high-volume website, you may experience performance degradation
 and latency on resource serving due to CPU overload, and, however - as the computational work is required also client side
 while decompressing - setting an higher compression level can result in an overall higher page load time
 especially nowadays when many clients are handled mobile devices with a low CPU profile.

 see also: http://www.gzip.org/algorithm.txt
+++
|[[compressionSupported]]`@compressionSupported`|`Boolean`|+++
Set whether the server should support gzip/deflate compression
 (serving compressed responses to clients advertising support for them with Accept-Encoding header)
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[decoderInitialBufferSize]]`@decoderInitialBufferSize`|`Number (int)`|+++
Set the initial buffer size for the HTTP decoder
+++
|[[decompressionSupported]]`@decompressionSupported`|`Boolean`|+++
Set whether the server supports decompression
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[handle100ContinueAutomatically]]`@handle100ContinueAutomatically`|`Boolean`|+++
Set whether 100 Continue should be handled automatically
+++
|[[host]]`@host`|`String`|+++
Set the host
+++
|[[http2ConnectionWindowSize]]`@http2ConnectionWindowSize`|`Number (int)`|+++
Set the default HTTP/2 connection window size. It overrides the initial window
 size set by link, so the connection window size
 is greater than for its streams, in order the data throughput.
 <p/>
 A value of <code>-1</code> reuses the initial window size setting.
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[maxChunkSize]]`@maxChunkSize`|`Number (int)`|+++
Set the maximum HTTP chunk size that link will receive
+++
|[[maxHeaderSize]]`@maxHeaderSize`|`Number (int)`|+++
Set the maximum length of all headers for HTTP/1.x .
+++
|[[maxInitialLineLength]]`@maxInitialLineLength`|`Number (int)`|+++
Set the maximum length of the initial line for HTTP/1.x (e.g. <code>"GET / HTTP/1.0"</code>)
+++
|[[maxWebSocketFrameSize]]`@maxWebSocketFrameSize`|`Number (int)`|+++
Set the maximum WebSocket frames size
+++
|[[maxWebSocketMessageSize]]`@maxWebSocketMessageSize`|`Number (int)`|+++
Set the maximum WebSocket message size
+++
|[[perFrameWebSocketCompressionSupported]]`@perFrameWebSocketCompressionSupported`|`Boolean`|+++
Enable or disable support for the WebSocket per-frame deflate compression extension.
+++
|[[perMessageWebSocketCompressionSupported]]`@perMessageWebSocketCompressionSupported`|`Boolean`|+++
Enable or disable support for WebSocket per-message deflate compression extension.
+++
|[[port]]`@port`|`Number (int)`|+++
Set the port
+++
|[[proxyProtocolTimeout]]`@proxyProtocolTimeout`|`Number (long)`|+++
Set the Proxy protocol timeout, default time unit is seconds.
+++
|[[proxyProtocolTimeoutUnit]]`@proxyProtocolTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the Proxy protocol timeout unit. If not specified, default is seconds.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[sni]]`@sni`|`Boolean`|+++
Set whether the server supports Server Name Indiciation
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|[[useProxyProtocol]]`@useProxyProtocol`|`Boolean`|+++
Set whether the server uses the HA Proxy protocol
+++
|[[webSocketAllowServerNoContext]]`@webSocketAllowServerNoContext`|`Boolean`|+++
Set whether the WebSocket server will accept the <code>server_no_context_takeover</code> parameter of the per-message
 deflate compression extension offered by the client.
+++
|[[webSocketCompressionLevel]]`@webSocketCompressionLevel`|`Number (int)`|+++
Set the WebSocket compression level.
+++
|[[webSocketPreferredClientNoContext]]`@webSocketPreferredClientNoContext`|`Boolean`|+++
Set whether the WebSocket server will accept the <code>client_no_context_takeover</code> parameter of the per-message
 deflate compression extension offered by the client.
+++
|[[webSocketSubProtocols]]`@webSocketSubProtocols`|`Array of String`|+++
Set the WebSocket list of sub-protocol supported by the server.
+++
|===

[[IndexModel]]
== IndexModel


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[key]]`@key`|`Json object`|+++
Get the index key
+++
|===

[[IndexOptions]]
== IndexOptions

++++
 Options used to configure index.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[background]]`@background`|`Boolean`|+++
Create the index in the background
+++
|[[bits]]`@bits`|`Number (Integer)`|+++
Gets the number of precision of the stored geohash value of the location data in 2d indexes.
+++
|[[bucketSize]]`@bucketSize`|`Number (Double)`|+++
Gets the specified the number of units within which to group the location values for geoHaystack Indexes
+++
|[[defaultLanguage]]`@defaultLanguage`|`String`|+++
Gets the language for a text index.

 <p>The language that determines the list of stop words and the rules for the stemmer and tokenizer.</p>
+++
|[[languageOverride]]`@languageOverride`|`String`|+++
Gets the name of the field that contains the language string.

 <p>For text indexes, the name of the field, in the collection's documents, that contains the override language for the document.</p>
+++
|[[max]]`@max`|`Number (Double)`|+++
Gets the upper inclusive boundary for the longitude and latitude values for 2d indexes..
+++
|[[min]]`@min`|`Number (Double)`|+++
Gets the lower inclusive boundary for the longitude and latitude values for 2d indexes..
+++
|[[name]]`@name`|`String`|+++
Gets the name of the index.
+++
|[[partialFilterExpression]]`@partialFilterExpression`|`Json object`|+++
Get the filter expression for the documents to be included in the index or null if not set
+++
|[[sparse]]`@sparse`|`Boolean`|+++
If true, the index only references documents with the specified field
+++
|[[sphereVersion]]`@sphereVersion`|`Number (Integer)`|+++
Gets the 2dsphere index version number.
+++
|[[storageEngine]]`@storageEngine`|`Json object`|+++
Gets the storage engine options document for this index.
+++
|[[textVersion]]`@textVersion`|`Number (Integer)`|+++
The text index version number.
+++
|[[unique]]`@unique`|`Boolean`|+++
Gets if the index should be unique.
+++
|[[version]]`@version`|`Number (Integer)`|+++
Gets the index version number.
+++
|[[weights]]`@weights`|`Json object`|+++
Gets the weighting object for use with a text index

 <p>A document that represents field and weight pairs. The weight is an integer ranging from 1 to 99,999 and denotes the significance
 of the field relative to the other indexed fields in terms of the score.</p>
+++
|===

[[JDBCAuthOptions]]
== JDBCAuthOptions

++++
 Options configuring JDBC authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[authenticationQuery]]`@authenticationQuery`|`String`|+++
Set the authentication query to use. Use this if you want to override the default authentication query.
+++
|[[config]]`@config`|`Json object`|+++
The configuration of the JDBC client: refer to the Vert.x JDBC Client configuration.
+++
|[[datasourceName]]`@datasourceName`|`String`|+++
Set the data source name to use, only use in shared mode.
+++
|[[permissionsQuery]]`@permissionsQuery`|`String`|+++
Set the permissions query to use. Use this if you want to override the default permissions query.
+++
|[[rolesPrefix]]`@rolesPrefix`|`String`|+++
Set the role prefix to distinguish from permissions when checking for isPermitted requests.
+++
|[[rolesQuery]]`@rolesQuery`|`String`|+++
Set the roles query to use. Use this if you want to override the default roles query.
+++
|[[shared]]`@shared`|`Boolean`|+++
Set whether the JDBC client is shared or non shared.
+++
|===

[[JDBCAuthenticationOptions]]
== JDBCAuthenticationOptions

++++
 Options configuring JDBC authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[authenticationQuery]]`@authenticationQuery`|`String`|+++
Set the authentication query to use. Use this if you want to override the
 default authentication query.
+++
|===

[[JDBCAuthorizationOptions]]
== JDBCAuthorizationOptions

++++
 Options configuring JDBC authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[permissionsQuery]]`@permissionsQuery`|`String`|+++
Set the permissions query to use. Use this if you want to override the
 default permissions query.
+++
|[[rolesQuery]]`@rolesQuery`|`String`|+++
Set the roles query to use. Use this if you want to override the default
 roles query.
+++
|===

[[JDBCConnectOptions]]
== JDBCConnectOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`@connectTimeout`|`Number (int)`|-
|[[dataSourceImplementation]]`@dataSourceImplementation`|`String`|-
|[[database]]`@database`|`String`|-
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|-
|[[jdbcUrl]]`@jdbcUrl`|`String`|-
|[[metricsEnabled]]`@metricsEnabled`|`Boolean`|-
|[[password]]`@password`|`String`|-
|[[user]]`@user`|`String`|-
|===

[[JWTAuthOptions]]
== JWTAuthOptions

++++
 Options describing how an JWT Auth should behave.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[jwks]]`@jwks`|`Array of Json object`|-
|[[permissionsClaimKey]]`@permissionsClaimKey`|`String`|-
|===

[[JWTOptions]]
== JWTOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[algorithm]]`@algorithm`|`String`|-
|[[audience]]`@audience`|`Array of String`|-
|[[audiences]]`@audiences`|`Array of String`|-
|[[expiresInMinutes]]`@expiresInMinutes`|`Number (int)`|-
|[[expiresInSeconds]]`@expiresInSeconds`|`Number (int)`|-
|[[header]]`@header`|`Json object`|-
|[[ignoreExpiration]]`@ignoreExpiration`|`Boolean`|-
|[[issuer]]`@issuer`|`String`|-
|[[leeway]]`@leeway`|`Number (int)`|-
|[[noTimestamp]]`@noTimestamp`|`Boolean`|-
|[[permissions]]`@permissions`|`Array of String`|+++
The permissions of this token.
+++
|[[scopeDelimiter]]`@scopeDelimiter`|`String`|+++

+++
|[[scopes]]`@scopes`|`Array of String`|+++

+++
|[[subject]]`@subject`|`String`|-
|===

[[JdkSSLEngineOptions]]
== JdkSSLEngineOptions

++++
 Configures a link to use the JDK ssl engine implementation.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[JksOptions]]
== JksOptions

++++
 Key or trust store options configuring private key and/or certificates based on Java Keystore files.
 <p>
 When used as a key store, it should point to a store containing a private key and its certificate.
 When used as a trust store, it should point to a store containing a list of trusted certificates.
 <p>
 The store can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = HttpServerOptions.httpServerOptions();
 options.setKeyStore(new JKSOptions().setPath("/mykeystore.jks").setPassword("foo"));
 </pre>

 Or directly provided as a buffer:
 <p>

 <pre>
 Buffer store = vertx.fileSystem().readFileBlocking("/mykeystore.jks");
 options.setKeyStore(new JKSOptions().setValue(store).setPassword("foo"));
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`@password`|`String`|+++
Set the password for the key store
+++
|[[path]]`@path`|`String`|+++
Set the path to the key store
+++
|[[value]]`@value`|`Buffer`|+++
Set the key store as a buffer
+++
|===

[[KeyStoreOptions]]
== KeyStoreOptions

++++
 Options describing how an JWT KeyStore should behave.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`@password`|`String`|-
|[[passwordProtection]]`@passwordProtection`|`String`|-
|[[path]]`@path`|`String`|-
|[[type]]`@type`|`String`|-
|===

[[MetricsOptions]]
== MetricsOptions

++++
 Vert.x metrics base configuration, this class can be extended by provider implementations to configure
 those specific implementations.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enabled]]`@enabled`|`Boolean`|+++
Set whether metrics will be enabled on the Vert.x instance.
+++
|===

[[MongoAuthOptions]]
== MongoAuthOptions

++++
 Options configuring Mongo authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collectionName]]`@collectionName`|`String`|+++
The property name to be used to set the name of the collection inside the config.
+++
|[[config]]`@config`|`Json object`|+++
The mongo client configuration: see Mongo Client documentation.
+++
|[[datasourceName]]`@datasourceName`|`String`|+++
The mongo data source name: see Mongo Client documentation.
+++
|[[passwordField]]`@passwordField`|`String`|+++
The property name to be used to set the name of the field, where the password is stored inside
+++
|[[permissionField]]`@permissionField`|`String`|+++
The property name to be used to set the name of the field, where the permissions are stored inside.
+++
|[[roleField]]`@roleField`|`String`|+++
The property name to be used to set the name of the field, where the roles are stored inside.
+++
|[[saltField]]`@saltField`|`String`|+++
The property name to be used to set the name of the field, where the SALT is stored inside.
+++
|[[saltStyle]]`@saltStyle`|`link:enums.html#HashSaltStyle[HashSaltStyle]`|+++
The property name to be used to set the name of the field, where the salt style is stored inside
+++
|[[shared]]`@shared`|`Boolean`|+++
Use a shared Mongo client or not.
+++
|[[usernameCredentialField]]`@usernameCredentialField`|`String`|+++
The property name to be used to set the name of the field, where the username for the credentials is stored inside.
+++
|[[usernameField]]`@usernameField`|`String`|+++
The property name to be used to set the name of the field, where the username is stored inside.
+++
|===

[[MongoAuthenticationOptions]]
== MongoAuthenticationOptions

++++
 Options configuring Mongo authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collectionName]]`@collectionName`|`String`|+++
The property name to be used to set the name of the collection inside the config.
+++
|[[passwordCredentialField]]`@passwordCredentialField`|`String`|-
|[[passwordField]]`@passwordField`|`String`|+++
The property name to be used to set the name of the field, where the password is stored inside
+++
|[[usernameCredentialField]]`@usernameCredentialField`|`String`|+++
The property name to be used to set the name of the field, where the username for the credentials is stored inside.
+++
|[[usernameField]]`@usernameField`|`String`|+++
The property name to be used to set the name of the field, where the username is stored inside.
+++
|===

[[MongoAuthorizationOptions]]
== MongoAuthorizationOptions

++++
 Options configuring Mongo authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collectionName]]`@collectionName`|`String`|+++
The property name to be used to set the name of the collection inside the config.
+++
|[[permissionField]]`@permissionField`|`String`|+++
The property name to be used to set the name of the field, where the permissions are stored inside.
+++
|[[roleField]]`@roleField`|`String`|+++
The property name to be used to set the name of the field, where the roles are stored inside.
+++
|[[usernameField]]`@usernameField`|`String`|+++
The property name to be used to set the name of the field, where the username is stored inside.
+++
|===

[[MongoClientBulkWriteResult]]
== MongoClientBulkWriteResult

++++
 Result propagated from mongodb driver bulk write result.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[deletedCount]]`@deletedCount`|`Number (long)`|+++
Returns the number of deleted documents
+++
|[[insertedCount]]`@insertedCount`|`Number (long)`|+++
Returns the number of inserted documents
+++
|[[matchedCount]]`@matchedCount`|`Number (long)`|+++
Returns the number of matched documents
+++
|[[modifiedCount]]`@modifiedCount`|`Number (long)`|+++
Returns the number of modified documents
+++
|[[upserts]]`@upserts`|`Array of Json object`|+++
An unmodifiable list of upsert data. Each entry has the index of the request that lead to the upsert, and the
 generated ID of the upsert.
+++
|===

[[MongoClientDeleteResult]]
== MongoClientDeleteResult

++++
 Result propagated from mongodb driver delete result.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[removedCount]]`@removedCount`|`Number (long)`|+++
Get the number of removed documents
+++
|===

[[MongoClientUpdateResult]]
== MongoClientUpdateResult

++++
 Result propagated from mongodb driver update result.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[docMatched]]`@docMatched`|`Number (long)`|+++
Get the number of documents that're matched
+++
|[[docModified]]`@docModified`|`Number (long)`|+++
Get the number of documents that're modified
+++
|[[docUpsertedId]]`@docUpsertedId`|`Json object`|+++
Get the document id that's upserted
+++
|===

[[NetClientOptions]]
== NetClientOptions

++++
 Options for configuring a link.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`@connectTimeout`|`Number (int)`|+++
Set the connect timeout
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[hostnameVerificationAlgorithm]]`@hostnameVerificationAlgorithm`|`String`|+++
Set the hostname verification algorithm interval
 To disable hostname verification, set hostnameVerificationAlgorithm to an empty String
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[localAddress]]`@localAddress`|`String`|+++
Set the local interface to bind for network connections. When the local address is null,
 it will pick any local address, the default local address is null.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[metricsName]]`@metricsName`|`String`|+++
Set the metrics name identifying the reported metrics, useful for grouping metrics
 with the same name.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reconnectAttempts]]`@reconnectAttempts`|`Number (int)`|+++
Set the value of reconnect attempts
+++
|[[reconnectInterval]]`@reconnectInterval`|`Number (long)`|+++
Set the reconnect interval
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[trustAll]]`@trustAll`|`Boolean`|+++
Set whether all server certificates should be trusted
+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|===

[[NetServerOptions]]
== NetServerOptions

++++
 Options for configuring a link.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`@acceptBacklog`|`Number (int)`|+++
Set the accept back log
+++
|[[clientAuth]]`@clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|+++
Set whether client auth is required
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[host]]`@host`|`String`|+++
Set the host
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[port]]`@port`|`Number (int)`|+++
Set the port
+++
|[[proxyProtocolTimeout]]`@proxyProtocolTimeout`|`Number (long)`|+++
Set the Proxy protocol timeout, default time unit is seconds.
+++
|[[proxyProtocolTimeoutUnit]]`@proxyProtocolTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the Proxy protocol timeout unit. If not specified, default is seconds.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[sni]]`@sni`|`Boolean`|+++
Set whether the server supports Server Name Indiciation
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|[[useProxyProtocol]]`@useProxyProtocol`|`Boolean`|+++
Set whether the server uses the HA Proxy protocol
+++
|===

[[NetworkOptions]]
== NetworkOptions

++++
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|===

[[OAuth2Options]]
== OAuth2Options

++++
 Options describing how an OAuth2  will make connections.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[authorizationPath]]`@authorizationPath`|`String`|+++
Get the Oauth2 authorization resource path. e.g.: /oauth/authorize
+++
|[[clientID]]`@clientID`|`String`|+++
Set the provider client id
+++
|[[clientSecret]]`@clientSecret`|`String`|+++
Set the provider client secret
+++
|[[clientSecretParameterName]]`@clientSecretParameterName`|`String`|+++
Override the HTTP form field name for client secret
+++
|[[extraParameters]]`@extraParameters`|`Json object`|+++
Set extra parameters to be sent to the provider on each request
+++
|[[flow]]`@flow`|`link:enums.html#OAuth2FlowType[OAuth2FlowType]`|-
|[[headers]]`@headers`|`Json object`|+++
Set custom headers to be sent with every request to the provider
+++
|[[introspectionPath]]`@introspectionPath`|`String`|+++
Set the provider token introspection resource path
+++
|[[jwkPath]]`@jwkPath`|`String`|-
|[[logoutPath]]`@logoutPath`|`String`|+++
Set the provider logout path
+++
|[[revocationPath]]`@revocationPath`|`String`|+++
Set the Oauth2 revocation resource path. e.g.: /oauth/revoke
+++
|[[scopeSeparator]]`@scopeSeparator`|`String`|+++
Set the provider scope separator
+++
|[[site]]`@site`|`String`|+++
Root URL for the provider without trailing slashes
+++
|[[tenant]]`@tenant`|`String`|+++
Sets an optional tenant. Tenants are used in some OpenID servers as placeholders for the URLs.
 The tenant should be set prior to any URL as it affects the way the URLs will be stored.

 Some provders may name this differently, for example: `realm`.
+++
|[[tokenPath]]`@tokenPath`|`String`|+++
Get the Oauth2 token resource path. e.g.: /oauth/token
+++
|[[useBasicAuthorizationHeader]]`@useBasicAuthorizationHeader`|`Boolean`|+++
Flag to use HTTP basic auth header with client id, client secret.
+++
|[[userAgent]]`@userAgent`|`String`|+++
Set a custom user agent to use when communicating to a provider
+++
|[[userInfoParameters]]`@userInfoParameters`|`Json object`|+++
Set custom parameters to be sent during the userInfo resource request
+++
|[[userInfoPath]]`@userInfoPath`|`String`|+++
Set the provider userInfo resource path
+++
|[[validateIssuer]]`@validateIssuer`|`Boolean`|-
|===

[[Oauth2Credentials]]
== Oauth2Credentials

++++
 Credentials specific to the link provider
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[code]]`@code`|`String`|-
|[[extra]]`@extra`|`Json object`|-
|[[redirectUri]]`@redirectUri`|`String`|-
|===

[[OpenOptions]]
== OpenOptions

++++
 Describes how an link should be opened.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[append]]`@append`|`Boolean`|+++
Whether the file should be opened in append mode. Defaults to <code>false</code>.
+++
|[[create]]`@create`|`Boolean`|+++
Set whether the file should be created if it does not already exist.
+++
|[[createNew]]`@createNew`|`Boolean`|+++
Set whether the file should be created and fail if it does exist already.
+++
|[[deleteOnClose]]`@deleteOnClose`|`Boolean`|+++
Set whether the file should be deleted when it's closed, or the JVM is shutdown.
+++
|[[dsync]]`@dsync`|`Boolean`|+++
Set whether every write to the file's content  ill be written synchronously to the underlying hardware.
+++
|[[perms]]`@perms`|`String`|+++
Set the permissions string
+++
|[[read]]`@read`|`Boolean`|+++
Set whether the file is to be opened for reading
+++
|[[sparse]]`@sparse`|`Boolean`|+++
Set whether a hint should be provided that the file to created is sparse
+++
|[[sync]]`@sync`|`Boolean`|+++
Set whether every write to the file's content and meta-data will be written synchronously to the underlying hardware.
+++
|[[truncateExisting]]`@truncateExisting`|`Boolean`|+++
Set whether the file should be truncated to zero length on opening if it exists and is opened for write
+++
|[[write]]`@write`|`Boolean`|+++
Set whether the file is to be opened for writing
+++
|===

[[OpenSSLEngineOptions]]
== OpenSSLEngineOptions

++++
 Configures a link to use OpenSsl.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[sessionCacheEnabled]]`@sessionCacheEnabled`|`Boolean`|+++
Set whether session cache is enabled in open SSL session server context
+++
|===

[[Option]]
== Option

++++
 Models command line options. Options are values passed to a command line interface using -x or --x. Supported
 syntaxes depend on the parser.
 <p/>
 Short name is generally used with a single dash, while long name requires a double-dash.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[argName]]`@argName`|`String`|+++
Sets te arg name for this option.
+++
|[[choices]]`@choices`|`Array of String`|+++
Sets the list of values accepted by this option. If the value set by the user does not match once of these
 values, a link exception is thrown.
+++
|[[defaultValue]]`@defaultValue`|`String`|+++
Sets the default value of this option
+++
|[[description]]`@description`|`String`|+++
Sets te description of this option.
+++
|[[flag]]`@flag`|`Boolean`|+++
Configures the current link to be a flag. It will be evaluated to <code>true</code> if it's found in
 the command line. If you need a flag that may receive a value, use, in this order:
 <code><pre>
   option.setFlag(true).setSingleValued(true)
 </pre></code>
+++
|[[help]]`@help`|`Boolean`|+++
Sets whether or not this option is a "help" option
+++
|[[hidden]]`@hidden`|`Boolean`|+++
Sets whether or not this option should be hidden
+++
|[[longName]]`@longName`|`String`|+++
Sets the long name of this option.
+++
|[[multiValued]]`@multiValued`|`Boolean`|+++
Sets whether or not this option can receive several values.
+++
|[[name]]`@name`|`String`|+++

+++
|[[required]]`@required`|`Boolean`|+++
Sets whether or not this option is mandatory.
+++
|[[shortName]]`@shortName`|`String`|+++
Sets the short name of this option.
+++
|[[singleValued]]`@singleValued`|`Boolean`|+++
Sets whether or not this option can receive a value.
+++
|===

[[PemKeyCertOptions]]
== PemKeyCertOptions

++++
 Key store options configuring a list of private key and its certificate based on
 <i>Privacy-enhanced Electronic Email</i> (PEM) files.
 <p>

 A key file must contain a <b>non encrypted</b> private key in <b>PKCS8</b> format wrapped in a PEM
 block, for example:
 <p>

 <pre>
 -----BEGIN PRIVATE KEY-----
 MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDV6zPk5WqLwS0a
 ...
 K5xBhtm1AhdnZjx5KfW3BecE
 -----END PRIVATE KEY-----
 </pre><p>

 Or contain a <b>non encrypted</b> private key in <b>PKCS1</b> format wrapped in a PEM
 block, for example:
 <p>

 <pre>
 -----BEGIN RSA PRIVATE KEY-----
 MIIEowIBAAKCAQEAlO4gbHeFb/fmbUF/tOJfNPJumJUEqgzAzx8MBXv9Acyw9IRa
 ...
 zJ14Yd+t2fsLYVs2H0gxaA4DW6neCzgY3eKpSU0EBHUCFSXp/1+/
 -----END RSA PRIVATE KEY-----
 </pre><p>

 A certificate file must contain an X.509 certificate wrapped in a PEM block, for example:
 <p>

 <pre>
 -----BEGIN CERTIFICATE-----
 MIIDezCCAmOgAwIBAgIEZOI/3TANBgkqhkiG9w0BAQsFADBuMRAwDgYDVQQGEwdV
 ...
 +tmLSvYS39O2nqIzzAUfztkYnUlZmB0l/mKkVqbGJA==
 -----END CERTIFICATE-----
 </pre>

 Keys and certificates can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemKeyCertOptions(new PemKeyCertOptions().setKeyPath("/mykey.pem").setCertPath("/mycert.pem"));
 </pre>

 Or directly provided as a buffer:<p>

 <pre>
 Buffer key = vertx.fileSystem().readFileBlocking("/mykey.pem");
 Buffer cert = vertx.fileSystem().readFileBlocking("/mycert.pem");
 options.setPemKeyCertOptions(new PemKeyCertOptions().setKeyValue(key).setCertValue(cert));
 </pre>

 Several key/certificate pairs can be used:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemKeyCertOptions(new PemKeyCertOptions()
    .addKeyPath("/mykey1.pem").addCertPath("/mycert1.pem")
    .addKeyPath("/mykey2.pem").addCertPath("/mycert2.pem"));
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[certPath]]`@certPath`|`String`|+++
Set the path of the first certificate, replacing the previous certificates paths
+++
|[[certPaths]]`@certPaths`|`Array of String`|+++
Set all the paths to the certificates files
+++
|[[certValue]]`@certValue`|`Buffer`|+++
Set the first certificate as a buffer, replacing the previous certificates buffers
+++
|[[certValues]]`@certValues`|`Array of Buffer`|+++
Set all the certificates as a list of buffer
+++
|[[keyPath]]`@keyPath`|`String`|+++
Set the path of the first key file, replacing the keys paths
+++
|[[keyPaths]]`@keyPaths`|`Array of String`|+++
Set all the paths to the keys files
+++
|[[keyValue]]`@keyValue`|`Buffer`|+++
Set the first key a a buffer, replacing the previous keys buffers
+++
|[[keyValues]]`@keyValues`|`Array of Buffer`|+++
Set all the keys as a list of buffer
+++
|===

[[PemTrustOptions]]
== PemTrustOptions

++++
 Certificate Authority options configuring certificates based on
 <i>Privacy-enhanced Electronic Email</i> (PEM) files. The options is configured with a list of
 validating certificates.
 <p>
 Validating certificates must contain X.509 certificates wrapped in a PEM block:<p>

 <pre>
 -----BEGIN CERTIFICATE-----
 MIIDezCCAmOgAwIBAgIEVmLkwTANBgkqhkiG9w0BAQsFADBuMRAwDgYDVQQGEwdV
 ...
 z5+DuODBJUQst141Jmgq8bS543IU/5apcKQeGNxEyQ==
 -----END CERTIFICATE-----
 </pre>

 The certificates can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemTrustOptions(new PemTrustOptions().addCertPath("/cert.pem"));
 </pre>

 Or directly provided as a buffer:
 <p>

 <pre>
 Buffer cert = vertx.fileSystem().readFileBlocking("/cert.pem");
 HttpServerOptions options = new HttpServerOptions();
 options.setPemTrustOptions(new PemTrustOptions().addCertValue(cert));
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[certPaths]]`@certPaths`|`Array of String`|+++
Add a certificate path
+++
|[[certValues]]`@certValues`|`Array of Buffer`|+++
Add a certificate value
+++
|===

[[PermittedOptions]]
== PermittedOptions

++++
 Represents a match to allow for inbound and outbound traffic.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`@address`|`String`|+++
The exact address the message is being sent to. If you want to allow messages based on
 an exact address you use this field.
+++
|[[addressRegex]]`@addressRegex`|`String`|+++
A regular expression that will be matched against the address. If you want to allow messages
 based on a regular expression you use this field. If the link value is specified
 this will be ignored.
+++
|[[match]]`@match`|`Json object`|+++
This allows you to allow messages based on their structure. Any fields in the match must exist in the
 message with the same values for them to be allowed. This currently only works with JSON messages.
+++
|[[requiredAuthority]]`@requiredAuthority`|`String`|+++
Declare a specific authority that user must have in order to allow messages
+++
|===

[[PfxOptions]]
== PfxOptions

++++
 Key or trust store options configuring private key and/or certificates based on PKCS#12 files.
 <p>
 When used as a key store, it should point to a store containing a private key and its certificate.
 When used as a trust store, it should point to a store containing a list of accepted certificates.
 <p>

 The store can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPfxKeyCertOptions(new PfxOptions().setPath("/mykeystore.p12").setPassword("foo"));
 </pre>

 Or directly provided as a buffer:<p>

 <pre>
 Buffer store = vertx.fileSystem().readFileBlocking("/mykeystore.p12");
 options.setPfxKeyCertOptions(new PfxOptions().setValue(store).setPassword("foo"));
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`@password`|`String`|+++
Set the password
+++
|[[path]]`@path`|`String`|+++
Set the path
+++
|[[value]]`@value`|`Buffer`|+++
Set the store as a buffer
+++
|===

[[ProxyOptions]]
== ProxyOptions

++++
 Proxy options for a net client or a net client.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[host]]`@host`|`String`|+++
Set proxy host.
+++
|[[password]]`@password`|`String`|+++
Set proxy password.
+++
|[[port]]`@port`|`Number (int)`|+++
Set proxy port.
+++
|[[type]]`@type`|`link:enums.html#ProxyType[ProxyType]`|+++
Set proxy type.

 <p>ProxyType can be HTTP, SOCKS4 and SOCKS5
+++
|[[username]]`@username`|`String`|+++
Set proxy username.
+++
|===

[[PubSecKeyOptions]]
== PubSecKeyOptions

++++
 Options describing Key stored in PEM format.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[algorithm]]`@algorithm`|`String`|-
|[[buffer]]`@buffer`|`String`|+++
The PEM or Secret key buffer
+++
|[[certificate]]`@certificate`|`Boolean`|-
|[[id]]`@id`|`String`|-
|[[publicKey]]`@publicKey`|`String`|+++

+++
|[[secretKey]]`@secretKey`|`String`|+++

+++
|[[symmetric]]`@symmetric`|`Boolean`|-
|===

[[RelayParty]]
== RelayParty


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[icon]]`@icon`|`String`|-
|[[id]]`@id`|`String`|-
|[[name]]`@name`|`String`|-
|===

[[RequestOptions]]
== RequestOptions

++++
 Options describing how an link will connect to make a request.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[absoluteURI]]`@absoluteURI`|`String`|+++
Parse an absolute URI to use, this will update the <code>ssl</code>, <code>host</code>,
 <code>port</code> and <code>uri</code> fields.
+++
|[[authority]]`@authority`|`String`|+++
Set the request authority.

 <p>For HTTP/2 the  pseudo header otherwise the  header.
+++
|[[followRedirects]]`@followRedirects`|`Boolean`|+++
Set whether to follow HTTP redirect
+++
|[[headers]]`@headers`|`String`|+++
Add a request header.
+++
|[[host]]`@host`|`String`|+++
Set the host name to be used by the client request.
+++
|[[port]]`@port`|`Number (Integer)`|+++
Set the port to be used by the client request.
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled.
+++
|[[timeout]]`@timeout`|`Number (long)`|+++
Sets the amount of time after which if the request does not return any data within the timeout period an
 link will be passed to the exception handler and
 the request will be closed.
+++
|[[uri]]`@uri`|`String`|+++
Set the request relative URI.
+++
|===

[[ResultSet]]
== ResultSet

++++
 Represents the results of a SQL query.
 <p>
 It contains a list for the column names of the results, and a list of <code>JsonArray</code> - one for each row of the
 results.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[columnNames]]`@columnNames`|`Array of String`|+++
Get the column names
+++
|[[numColumns]]`@numColumns`|`Number (int)`|+++
Return the number of columns in the result set
+++
|[[numRows]]`@numRows`|`Number (int)`|+++
Return the number of rows in the result set
+++
|[[output]]`@output`|`Json array`|+++
Get the registered outputs
+++
|[[results]]`@results`|`Array of Json array`|+++
Get the results
+++
|[[rows]]`@rows`|`Array of Json object`|+++
Get the rows - each row represented as a JsonObject where the keys are the column names and the values are
 the column values.

 Beware that it's legal for a query result in SQL to contain duplicate column names, in which case one will
 overwrite the other if using this method. If that's the case use link instead.

 Be aware that column names are defined as returned by the database, this means that even if your SQL statement
 is for example: <pre>SELECT a, b FROM table</pre> the column names are not required to be: <pre>a</pre> and
 <pre>b</pre> and could be in fact <pre>A</pre> and <pre>B</pre>.

 For cases when there is the need for case insentivitity you should see link
+++
|===

[[SQLOptions]]
== SQLOptions

++++
 Represents the options one can use to customize the unwrapped connection/statement/resultset types
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[autoGeneratedKeys]]`@autoGeneratedKeys`|`Boolean`|-
|[[autoGeneratedKeysIndexes]]`@autoGeneratedKeysIndexes`|`Json array`|-
|[[catalog]]`@catalog`|`String`|-
|[[fetchDirection]]`@fetchDirection`|`link:enums.html#FetchDirection[FetchDirection]`|-
|[[fetchSize]]`@fetchSize`|`Number (int)`|-
|[[queryTimeout]]`@queryTimeout`|`Number (int)`|-
|[[readOnly]]`@readOnly`|`Boolean`|-
|[[resultSetConcurrency]]`@resultSetConcurrency`|`link:enums.html#ResultSetConcurrency[ResultSetConcurrency]`|-
|[[resultSetType]]`@resultSetType`|`link:enums.html#ResultSetType[ResultSetType]`|-
|[[schema]]`@schema`|`String`|-
|[[transactionIsolation]]`@transactionIsolation`|`link:enums.html#TransactionIsolation[TransactionIsolation]`|-
|===

[[ShiroAuthOptions]]
== ShiroAuthOptions

++++
 Shiro auth configuration options, see Vert.x Auth Shiro component and/or Apache Shiro project.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Set the Shiro auth config.
+++
|[[type]]`@type`|`link:enums.html#ShiroAuthRealmType[ShiroAuthRealmType]`|+++
Set the Shiro auth options type.
+++
|===

[[SockJSBridgeOptions]]
== SockJSBridgeOptions

++++
 Options for configuring the event bus bridge.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[maxAddressLength]]`@maxAddressLength`|`Number (int)`|-
|[[maxHandlersPerSocket]]`@maxHandlersPerSocket`|`Number (int)`|-
|[[pingTimeout]]`@pingTimeout`|`Number (long)`|-
|[[replyTimeout]]`@replyTimeout`|`Number (long)`|-
|===

[[SockJSHandlerOptions]]
== SockJSHandlerOptions

++++
 Options for configuring a SockJS handler
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[disabledTransports]]`@disabledTransports`|`Array of String`|-
|[[heartbeatInterval]]`@heartbeatInterval`|`Number (long)`|-
|[[insertJSESSIONID]]`@insertJSESSIONID`|`Boolean`|-
|[[libraryURL]]`@libraryURL`|`String`|-
|[[maxBytesStreaming]]`@maxBytesStreaming`|`Number (int)`|-
|[[sessionTimeout]]`@sessionTimeout`|`Number (long)`|-
|===

[[StreamPriority]]
== StreamPriority

++++
 This class represents HTTP/2 stream priority defined in RFC 7540 clause 5.3
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[dependency]]`@dependency`|`Number (int)`|+++
Set the priority dependency value.
+++
|[[exclusive]]`@exclusive`|`Boolean`|+++
Set the priority exclusive value.
+++
|[[weight]]`@weight`|`Number (short)`|+++
Set the priority weight.
+++
|===

[[TCPSSLOptions]]
== TCPSSLOptions

++++
 Base class. TCP and SSL related options
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|===

[[TokenCredentials]]
== TokenCredentials

++++
 Credentials used by any link that requires Tokens, such as OAuth2 or JWT
 to perform its authentication
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[token]]`@token`|`String`|-
|===

[[TracingOptions]]
== TracingOptions

++++
 Vert.x tracing base configuration, this class can be extended by provider implementations to configure
 those specific implementations.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[UpdateOptions]]
== UpdateOptions

++++
 Options for configuring updates.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[arrayFilters]]`@arrayFilters`|`Json array`|+++
Set the arrayFilters option
+++
|[[multi]]`@multi`|`Boolean`|+++
Set whether multi is enabled
+++
|[[returningNewDocument]]`@returningNewDocument`|`Boolean`|+++
Set whether new document property is enabled. Valid only on findOneAnd* methods.
+++
|[[upsert]]`@upsert`|`Boolean`|+++
Set whether upsert is enabled
+++
|[[writeOption]]`@writeOption`|`link:enums.html#WriteOption[WriteOption]`|+++
Set the write option
+++
|===

[[UpdateResult]]
== UpdateResult

++++
 Represents the result of an update/insert/delete operation on the database.
 <p>
 The number of rows updated is available with link and any generated
 keys are available with link.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[keys]]`@keys`|`Json array`|+++
Get any generated keys
+++
|[[updated]]`@updated`|`Number (int)`|+++
Get the number of rows updated
+++
|===

[[UsernamePasswordCredentials]]
== UsernamePasswordCredentials

++++
 Credentials used by any link that requires tokens, for example JWT, Oauth2, OpenId Connect
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`@password`|`String`|-
|[[username]]`@username`|`String`|-
|===

[[VertxOptions]]
== VertxOptions

++++
 Instances of this class are used to configure link instances.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[blockedThreadCheckInterval]]`@blockedThreadCheckInterval`|`Number (long)`|+++
Sets the value of blocked thread check period, in link.
 <p>
 The default value of link is
+++
|[[blockedThreadCheckIntervalUnit]]`@blockedThreadCheckIntervalUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the time unit of <code>blockedThreadCheckInterval</code>.
+++
|[[eventLoopPoolSize]]`@eventLoopPoolSize`|`Number (int)`|+++
Set the number of event loop threads to be used by the Vert.x instance.
+++
|[[haEnabled]]`@haEnabled`|`Boolean`|+++
Set whether HA will be enabled on the Vert.x instance.
+++
|[[haGroup]]`@haGroup`|`String`|+++
Set the HA group to be used when HA is enabled.
+++
|[[internalBlockingPoolSize]]`@internalBlockingPoolSize`|`Number (int)`|+++
Set the value of internal blocking pool size
+++
|[[maxEventLoopExecuteTime]]`@maxEventLoopExecuteTime`|`Number (long)`|+++
Sets the value of max event loop execute time, in link.
 <p>
 The default value of linkis
+++
|[[maxEventLoopExecuteTimeUnit]]`@maxEventLoopExecuteTimeUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the time unit of <code>maxEventLoopExecuteTime</code>.
+++
|[[maxWorkerExecuteTime]]`@maxWorkerExecuteTime`|`Number (long)`|+++
Sets the value of max worker execute time, in link.
 <p>
 The default value of link is
+++
|[[maxWorkerExecuteTimeUnit]]`@maxWorkerExecuteTimeUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the time unit of <code>maxWorkerExecuteTime</code>.
+++
|[[preferNativeTransport]]`@preferNativeTransport`|`Boolean`|+++
Set wether to prefer the native transport to the JDK transport.
+++
|[[quorumSize]]`@quorumSize`|`Number (int)`|+++
Set the quorum size to be used when HA is enabled.
+++
|[[warningExceptionTime]]`@warningExceptionTime`|`Number (long)`|+++
Set the threshold value above this, the blocked warning contains a stack trace. in link.
 The default value of link is
+++
|[[warningExceptionTimeUnit]]`@warningExceptionTimeUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the time unit of <code>warningExceptionTime</code>.
+++
|[[workerPoolSize]]`@workerPoolSize`|`Number (int)`|+++
Set the maximum number of worker threads to be used by the Vert.x instance.
+++
|===

[[WebAuthnCredentials]]
== WebAuthnCredentials


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[challenge]]`@challenge`|`String`|-
|[[username]]`@username`|`String`|-
|[[webauthn]]`@webauthn`|`Json object`|-
|===

[[WebAuthnOptions]]
== WebAuthnOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[attestation]]`@attestation`|`link:enums.html#Attestation[Attestation]`|-
|[[authenticatorAttachment]]`@authenticatorAttachment`|`link:enums.html#AuthenticatorAttachment[AuthenticatorAttachment]`|-
|[[authenticatorSelection]]`@authenticatorSelection`|`Json object`|-
|[[challengeLength]]`@challengeLength`|`Number (int)`|-
|[[origin]]`@origin`|`String`|-
|[[pubKeyCredParams]]`@pubKeyCredParams`|`Array of String`|-
|[[requireResidentKey]]`@requireResidentKey`|`Boolean`|-
|[[timeout]]`@timeout`|`Number (int)`|-
|[[transports]]`@transports`|`Array of String`|-
|[[userVerification]]`@userVerification`|`link:enums.html#UserVerification[UserVerification]`|-
|===

[[WebClientOptions]]
== WebClientOptions

++++
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[alpnVersions]]`@alpnVersions`|`Array of link:enums.html#HttpVersion[HttpVersion]`|+++
Set the list of protocol versions to provide to the server during the Application-Layer Protocol Negotiation.
 When the list is empty, the client provides a best effort list according to link:

 <ul>
   <li>: [ "h2", "http/1.1" ]</li>
   <li>otherwise: [link]</li>
 </ul>
+++
|[[connectTimeout]]`@connectTimeout`|`Number (int)`|+++
Set the connect timeout
+++
|[[crlPaths]]`@crlPaths`|`Array of String`|+++
Add a CRL path
+++
|[[crlValues]]`@crlValues`|`Array of Buffer`|+++
Add a CRL value
+++
|[[decoderInitialBufferSize]]`@decoderInitialBufferSize`|`Number (int)`|+++
set to <code>initialBufferSizeHttpDecoder</code> the initial buffer of the HttpDecoder.
+++
|[[defaultHost]]`@defaultHost`|`String`|+++
Set the default host name to be used by this client in requests if none is provided when making the request.
+++
|[[defaultPort]]`@defaultPort`|`Number (int)`|+++
Set the default port to be used by this client in requests if none is provided when making the request.
+++
|[[enabledCipherSuites]]`@enabledCipherSuites`|`Array of String`|+++
Add an enabled cipher suite, appended to the ordered suites.
+++
|[[enabledSecureTransportProtocols]]`@enabledSecureTransportProtocols`|`Array of String`|+++
Sets the list of enabled SSL/TLS protocols.
+++
|[[followRedirects]]`@followRedirects`|`Boolean`|+++
Configure the default behavior of the client to follow HTTP <code>30x</code> redirections.
+++
|[[forceSni]]`@forceSni`|`Boolean`|+++
By default, the server name is only sent for Fully Qualified Domain Name (FQDN), setting
 this property to <code>true</code> forces the server name to be always sent.
+++
|[[http2ClearTextUpgrade]]`@http2ClearTextUpgrade`|`Boolean`|+++
Set to <code>true</code> when an <i>h2c</i> connection is established using an HTTP/1.1 upgrade request, and <code>false</code>
 when an <i>h2c</i> connection is established directly (with prior knowledge).
+++
|[[http2ConnectionWindowSize]]`@http2ConnectionWindowSize`|`Number (int)`|+++
Set the default HTTP/2 connection window size. It overrides the initial window
 size set by , so the connection window size
 is greater than for its streams, in order the data throughput.
 <p/>
 A value of <code>-1</code> reuses the initial window size setting.
+++
|[[http2KeepAliveTimeout]]`@http2KeepAliveTimeout`|`Number (int)`|+++
Set the keep alive timeout for HTTP/2 connections, in seconds.
 <p/>
 This value determines how long a connection remains unused in the pool before being evicted and closed.
 <p/>
 A timeout of <code>0</code> means there is no timeout.
+++
|[[http2MaxPoolSize]]`@http2MaxPoolSize`|`Number (int)`|+++
Set the maximum pool size for HTTP/2 connections
+++
|[[http2MultiplexingLimit]]`@http2MultiplexingLimit`|`Number (int)`|+++
Set a client limit of the number concurrent streams for each HTTP/2 connection, this limits the number
 of streams the client can create for a connection. The effective number of streams for a
 connection is the min of this value and the server's initial settings.
 <p/>
 Setting the value to <code>-1</code> means to use the value sent by the server's initial settings.
 <code>-1</code> is the default value.
+++
|[[idleTimeout]]`@idleTimeout`|`Number (int)`|+++
Set the idle timeout, default time unit is seconds. Zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.

 If you want change default time unit, use link
+++
|[[idleTimeoutUnit]]`@idleTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the idle timeout unit. If not specified, default is seconds.
+++
|[[keepAlive]]`@keepAlive`|`Boolean`|+++
Set whether keep alive is enabled on the client
+++
|[[keepAliveTimeout]]`@keepAliveTimeout`|`Number (int)`|+++
Set the keep alive timeout for HTTP/1.x, in seconds.
 <p/>
 This value determines how long a connection remains unused in the pool before being evicted and closed.
 <p/>
 A timeout of <code>0</code> means there is no timeout.
+++
|[[localAddress]]`@localAddress`|`String`|+++
Set the local interface to bind for network connections. When the local address is null,
 it will pick any local address, the default local address is null.
+++
|[[logActivity]]`@logActivity`|`Boolean`|+++
Set to true to enabled network activity logging: Netty's pipeline is configured for logging on Netty's logger.
+++
|[[maxChunkSize]]`@maxChunkSize`|`Number (int)`|+++
Set the maximum HTTP chunk size
+++
|[[maxHeaderSize]]`@maxHeaderSize`|`Number (int)`|+++
Set the maximum length of all headers for HTTP/1.x .
+++
|[[maxInitialLineLength]]`@maxInitialLineLength`|`Number (int)`|+++
Set the maximum length of the initial line for HTTP/1.x (e.g. <code>"HTTP/1.1 200 OK"</code>)
+++
|[[maxPoolSize]]`@maxPoolSize`|`Number (int)`|+++
Set the maximum pool size for connections
+++
|[[maxRedirects]]`@maxRedirects`|`Number (int)`|+++
Set to <code>maxRedirects</code> the maximum number of redirection a request can follow.
+++
|[[maxWaitQueueSize]]`@maxWaitQueueSize`|`Number (int)`|+++
Set the maximum requests allowed in the wait queue, any requests beyond the max size will result in
 a ConnectionPoolTooBusyException.  If the value is set to a negative number then the queue will be unbounded.
+++
|[[maxWebSocketFrameSize]]`@maxWebSocketFrameSize`|`Number (int)`|+++
Set the max WebSocket frame size
+++
|[[maxWebSocketMessageSize]]`@maxWebSocketMessageSize`|`Number (int)`|+++
Set the max WebSocket message size
+++
|[[metricsName]]`@metricsName`|`String`|+++
Set the metrics name identifying the reported metrics, useful for grouping metrics
 with the same name.
+++
|[[pipelining]]`@pipelining`|`Boolean`|+++
Set whether pipe-lining is enabled on the client
+++
|[[pipeliningLimit]]`@pipeliningLimit`|`Number (int)`|+++
Set the limit of pending requests a pipe-lined HTTP/1 connection can send.
+++
|[[poolCleanerPeriod]]`@poolCleanerPeriod`|`Number (int)`|+++
Set the connection pool cleaner period in milli seconds, a non positive value disables expiration checks and connections
 will remain in the pool until they are closed.
+++
|[[protocolVersion]]`@protocolVersion`|`link:enums.html#HttpVersion[HttpVersion]`|+++
Set the protocol version.
+++
|[[receiveBufferSize]]`@receiveBufferSize`|`Number (int)`|+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`@reuseAddress`|`Boolean`|+++
Set the value of reuse address
+++
|[[reusePort]]`@reusePort`|`Boolean`|+++
Set the value of reuse port.
 <p/>
 This is only supported by native transports.
+++
|[[sendBufferSize]]`@sendBufferSize`|`Number (int)`|+++
Set the TCP send buffer size
+++
|[[sendUnmaskedFrames]]`@sendUnmaskedFrames`|`Boolean`|+++
Set <code>true</code> when the client wants to skip frame masking.
 <p>
 You may want to set it <code>true</code> on server by server WebSocket communication: in this case you are by passing
 RFC6455 protocol.
 <p>
 It's <code>false</code> as default.
+++
|[[soLinger]]`@soLinger`|`Number (int)`|+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled
+++
|[[sslHandshakeTimeout]]`@sslHandshakeTimeout`|`Number (long)`|+++
Set the SSL handshake timeout, default time unit is seconds.
+++
|[[sslHandshakeTimeoutUnit]]`@sslHandshakeTimeoutUnit`|`link:enums.html#TimeUnit[TimeUnit]`|+++
Set the SSL handshake timeout unit. If not specified, default is seconds.
+++
|[[tcpCork]]`@tcpCork`|`Boolean`|+++
Enable the <code>TCP_CORK</code> option - only with linux native transport.
+++
|[[tcpFastOpen]]`@tcpFastOpen`|`Boolean`|+++
Enable the <code>TCP_FASTOPEN</code> option - only with linux native transport.
+++
|[[tcpKeepAlive]]`@tcpKeepAlive`|`Boolean`|+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`@tcpNoDelay`|`Boolean`|+++
Set whether TCP no delay is enabled
+++
|[[tcpQuickAck]]`@tcpQuickAck`|`Boolean`|+++
Enable the <code>TCP_QUICKACK</code> option - only with linux native transport.
+++
|[[trafficClass]]`@trafficClass`|`Number (int)`|+++
Set the value of traffic class
+++
|[[trustAll]]`@trustAll`|`Boolean`|+++
Set whether all server certificates should be trusted
+++
|[[tryUseCompression]]`@tryUseCompression`|`Boolean`|+++
Set whether compression is enabled
+++
|[[tryUsePerFrameWebSocketCompression]]`@tryUsePerFrameWebSocketCompression`|`Boolean`|+++
Set whether the client will offer the WebSocket per-frame deflate compression extension.
+++
|[[tryUsePerMessageWebSocketCompression]]`@tryUsePerMessageWebSocketCompression`|`Boolean`|+++
Set whether the client will offer the WebSocket per-message deflate compression extension.
+++
|[[tryWebSocketDeflateFrameCompression]]`@tryWebSocketDeflateFrameCompression`|`Boolean`|+++

+++
|[[useAlpn]]`@useAlpn`|`Boolean`|+++
Set the ALPN usage.
+++
|[[userAgent]]`@userAgent`|`String`|+++
Sets the Web Client user agent header. Defaults to Vert.x-WebClient/&lt;version&gt;.
+++
|[[userAgentEnabled]]`@userAgentEnabled`|`Boolean`|+++
Sets whether the Web Client should send a user agent header. Defaults to true.
+++
|[[verifyHost]]`@verifyHost`|`Boolean`|+++
Set whether hostname verification is enabled
+++
|[[webSocketCompressionAllowClientNoContext]]`@webSocketCompressionAllowClientNoContext`|`Boolean`|+++
Set whether the <code>client_no_context_takeover</code> parameter of the WebSocket per-message
 deflate compression extension will be offered.
+++
|[[webSocketCompressionLevel]]`@webSocketCompressionLevel`|`Number (int)`|+++
Set the WebSocket deflate compression level.
+++
|[[webSocketCompressionRequestServerNoContext]]`@webSocketCompressionRequestServerNoContext`|`Boolean`|+++
Set whether the <code>server_no_context_takeover</code> parameter of the WebSocket per-message
 deflate compression extension will be offered.
+++
|===

[[WebSocketConnectOptions]]
== WebSocketConnectOptions

++++
 Options describing how an link connect a link.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[absoluteURI]]`@absoluteURI`|`String`|+++
Parse an absolute URI to use, this will update the <code>ssl</code>, <code>host</code>,
 <code>port</code> and <code>uri</code> fields.
+++
|[[authority]]`@authority`|`String`|+++
Set the request authority.

 <p>For HTTP/2 the  pseudo header otherwise the  header.
+++
|[[followRedirects]]`@followRedirects`|`Boolean`|+++
Set whether to follow HTTP redirect
+++
|[[headers]]`@headers`|`String`|+++
Add a request header.
+++
|[[host]]`@host`|`String`|+++
Set the host name to be used by the client request.
+++
|[[port]]`@port`|`Number (Integer)`|+++
Set the port to be used by the client request.
+++
|[[ssl]]`@ssl`|`Boolean`|+++
Set whether SSL/TLS is enabled.
+++
|[[subProtocols]]`@subProtocols`|`Array of String`|+++
Set the WebSocket sub protocols to use.
+++
|[[timeout]]`@timeout`|`Number (long)`|+++
Sets the amount of time after which if the request does not return any data within the timeout period an
 link will be passed to the exception handler and
 the request will be closed.
+++
|[[uri]]`@uri`|`String`|+++
Set the request relative URI.
+++
|[[version]]`@version`|`link:enums.html#WebsocketVersion[WebsocketVersion]`|+++
Set the WebSocket version.
+++
|===

